services:
  app:
    extends:
      file: docker-compose.coolify.yml
      service: app
    ports: ["127.0.0.1:3019:10000"]
  worker:
    extends:
      file: docker-compose.coolify.yml
      service: worker
  postgres:
    extends:
      file: docker-compose.coolify.yml
      service: postgres
  redis:
    extends:
      file: docker-compose.coolify.yml
      service: redis
volumes:
  dados:
  postgres-dados:
  redis-dados:
